#  __   __   __  ___  ___
# /  ' /  \ |__)  |  |__  \_/
# \__. \__/ |  \  |  |___ / \

# VK API
vk_api:
  # Токен
  token: TOKEN

# Основное
general:
  # Шанс генерации сообщения
  chance: 20
  # Минимальное кол-во слов в тексте
  min_words: 5
  # Максимальное кол-во символов в тексте
  max_symbols: 250
  # ID бесед, в которых бот активен
  active_chats: all
  # Сохранение сообщений пользователей
  # * Одинаковые строки не сохраняются
  data_save: true

# Формат текста
format:
  # Строчные буквы
  to_lower_case: true
  # Заглавная буква в начале
  capitalize_word: true
  # Точка в конце
  end_dot: true