#  __  __   __  ___  ___
# /   /  \ |__)  |  |__  \_/
# \__ \__/ |  \  |  |___ / \

# Настройки VK API
longpoll:
  # Токен доступа
  token: TOKEN
  # Версия
  version: 5.131
  # ID группы с ботом
  # * При работе на странице укажите 0
  group_id: ID

# Отправка сообщений
messages:
  # Шанс генерации текста
  chance: 100
  # Максимальное кол-во символов в тексте
  # * Если символов в тексте будет больше данного значения сообщение не отправится
  symbols_limit: 250
  # ID бесед, в которых бот активен
  # Чтобы бот работал везде поставьте значение <<all>>
  active_chats: all
  # Форматирование текста
  format: false
  # Имитация написания текста
  # * При включении появляется задержка перед отправкой сообщений
  writing_imitation: true

# Генерация текста
generation:
  # Минимальное кол-во слов в генерируемом тексте
  min_words: 5

# Настройки БД
database:
  # Сохранение сообщений пользователей
  # * Одинаковые строки не сохраняются
  data_save: true