#  __   __   __  ___  ___
# /  ' /  \ |__)  |  |__  \_/
# \__, \__/ |  \  |  |___ / \

# VK API
vk_api:
  # Токен
  token: TOKEN

# Отправка сообщений
messages:
  # Шанс генерации
  chance: 20
  # Максимальное кол-во символов в тексте
  symbols_limit: 250
  # ID бесед, в которых бот активен
  active_chats: all
  # Форматирование текста
  format:
    # Строчные буквы
    to_lower_case: true
    # Заглавная буква в начале
    capitalize_word: true
    # Точка в конце
    end_dot: true

# Генерация текста
generation:
  # Минимальное кол-во слов в генерируемом тексте
  min_words: 5

# Настройки БД
database:
  # Сохранение сообщений пользователей
  # * Одинаковые строки не сохраняются
  data_save: true